'use client'

import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { useLanguage } from '@/hooks/use-language'

export default function PWATester() {
  const { t } = useLanguage()
  const [isInstallable, setIsInstallable] = useState(false)
  const [isInstalled, setIsInstalled] = useState(false)
  const [deferredPrompt, setDeferredPrompt] = useState<any>(null)
  const [pwaStatus, setPwaStatus] = useState<string[]>([])

  useEffect(() => {
    const status: string[] = []

    // Check if running in standalone mode (installed PWA)
    if (window.matchMedia('(display-mode: standalone)').matches) {
      status.push(t('pwa.status.standalone'))
      setIsInstalled(true)
    } else {
      status.push(t('pwa.status.browser'))
    }

    // Check if service worker is registered
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.getRegistrations().then(registrations => {
        if (registrations.length > 0) {
          status.push(t('pwa.status.swRegistered'))
        } else {
          status.push(t('pwa.status.swNotRegistered'))
        }
      })
    }

    // Check manifest
    if ('manifest' in document.createElement('link')) {
      status.push(t('pwa.status.manifestSupported'))
    }

    // Check HTTPS or localhost
    if (location.protocol === 'https:' || location.hostname === 'localhost') {
      status.push(t('pwa.status.httpsLocalhost'))
    } else {
      status.push(t('pwa.status.httpsRequired'))
    }

    // Check beforeinstallprompt support
    if ('onbeforeinstallprompt' in window) {
      status.push(t('pwa.status.promptSupported'))
    }

    const handleBeforeInstallPrompt = (e: any) => {
      e.preventDefault()
      setDeferredPrompt(e)
      setIsInstallable(true)
      status.push(t('pwa.status.ready'))
      setPwaStatus(status)
    }

    const handleAppInstalled = () => {
      status.push(t('pwa.status.success'))
      setIsInstalled(true)
      setIsInstallable(false)
      setPwaStatus([...status])
    }

    window.addEventListener('beforeinstallprompt', handleBeforeInstallPrompt)
    window.addEventListener('appinstalled', handleAppInstalled)

    setPwaStatus(status)

    return () => {
      window.removeEventListener('beforeinstallprompt', handleBeforeInstallPrompt)
      window.removeEventListener('appinstalled', handleAppInstalled)
    }
  }, [])

  const handleInstall = async () => {
    if (!deferredPrompt) return

    deferredPrompt.prompt()
    const { outcome } = await deferredPrompt.userChoice

    if (outcome === 'accepted') {
      console.log('Foydalanuvchi o\'rnatishni qabul qildi')
    } else {
      console.log('Foydalanuvchi o\'rnatishni rad etdi')
    }

    setDeferredPrompt(null)
    setIsInstallable(false)
  }

  const getWebAPKPackageName = () => {
    // WebAPK package name is generated by Chrome based on origin
    const origin = window.location.origin
    // This is a simplified representation - actual package name is generated by Chrome
    return `org.chromium.webapk.${btoa(origin).replace(/[^a-zA-Z0-9]/g, '').toLowerCase()}_v2`
  }

  return (
    <div className="container mx-auto p-4 max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            📱 PWA/WebAPK Test
            <Badge variant={isInstalled ? "default" : "secondary"}>
              {isInstalled ? t("pwa.installed") : t("pwa.notInstalled")}
            </Badge>
          </CardTitle>
          <CardDescription>
            PWA funksiyalarini tekshirish va WebAPK o'rnatish
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h3 className="font-semibold mb-2">PWA Status:</h3>
            <div className="space-y-1">
              {pwaStatus.map((status, index) => (
                <div key={index} className="text-sm">{status}</div>
              ))}
            </div>
          </div>

          <div>
            <h3 className="font-semibold mb-2">WebAPK Package Name:</h3>
            <code className="bg-gray-100 px-2 py-1 rounded text-sm break-all">
              {getWebAPKPackageName()}
            </code>
            <p className="text-xs text-gray-600 mt-1">
              Bu Chrome tomonidan avtomatik yaratiladi
            </p>
          </div>

          {isInstallable && (
            <div>
              <h3 className="font-semibold mb-2">O'rnatish:</h3>
              <Button onClick={handleInstall} className="w-full">
                {t("pwa.installWebAPK")}
              </Button>
            </div>
          )}

          <div>
            <h3 className="font-semibold mb-2">Test qilish uchun:</h3>
            <div className="space-y-2 text-sm">
              <div>1. Chrome brauzerida oching</div>
              <div>2. Address bar da "Install app" tugmasini qidiring</div>
              <div>3. Yoki 3 nuqta menu > "Add to home screen"</div>
              <div>4. O'rnatgandan keyin Android da APK sifatida ishlaydi</div>
            </div>
          </div>

          <div>
            <h3 className="font-semibold mb-2">WebAPK xususiyatlari:</h3>
            <div className="space-y-1 text-sm">
              <div>✅ O'z APK fayli (org.chromium.webapk.*)</div>
              <div>✅ Play Store da ko'rinmaydi</div>
              <div>✅ Chrome orqali boshqariladi</div>
              <div>✅ Avtomatik yangilanadi</div>
              <div>✅ Offline ishlaydi</div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}